spark_config:
  master_url: "spark://155.230.34.51:32177"
  driver_host: "155.230.34.51"
  driver_bindAddress: "0.0.0.0"
  executor_instances: 3
  executor_cores: 4
  executor_memory: "8G"
  app_name: "FastAPI-Spark Integration"
  kafka_bootstrap_servers: "155.230.34.51:32100,155.230.34.52:32100,155.230.34.53:32100"
  kafka_jars: [
    "jars/kafka-clients-3.4.1.jar",
    "jars/slf4j-api-2.0.7.jar",
    "jars/snappy-java-1.1.10.3.jar",
    "jars/spark-sql-kafka-0-10_2.12-3.5.1.jar",
    "jars/spark-streaming-kafka-0-10_2.12-3.5.1.jar",
    "jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar",
    "jars/commons-pool2-2.11.1.jar",
    "jars/spark-protobuf_2.12-3.5.1.jar"
  ]